backend:
  name: git-gateway
  branch: nojs

publish_mode: editorial_workflow
site_url: https://nojs--api-puszcza.netlify.app
logo_url: /19pdh.png
locale: 'pl'

media_folder: 'wpisy/assets'
public_folder: '/assets'

collections:
  - name: posts
    label: 'Wpisy'
    label_singular: 'wpis'
    folder: 'wpisy/kronika'
    slug: '{{title}}'
    path: 'kronika/{{year}}/{{month}}/{{day}}/{{slug}}'
    preview_path: 'kronika/{{year}}/{{month}}/{{day}}/{{title}}'
    preview_path_date_field: 'date'
    create: true
    editor:
      preview: true
    fields:
      - label: 'Tytuł'
        name: title
        widget: string
        required: true

      - label: 'Kategorie/Tagi'
        name: category
        widget: list
        required: false

      - label: 'Wpis'
        name: body
        widget: markdown
        required: true
  - name: "pages"
    label: "Strony"
    files:
      - label: "Do pobrania"
        name: "download"
        file: "wpisy/do-pobrania.md"
        fields:
          - label: "Treść"
            name: "body"
            widget: "markdown"

      - label: "Kontakt"
        name: "contact"
        file: "wpisy/kontakt.md"
        fields:
          - label: "Treść"
            name: "body"
            widget: "markdown"
