backend:
  name: git-gateway

#publish_mode: editorial_workflow
display_url: https://puszcza.netlify.com
site_url: https://puszcza.netlify.com
locale: 'pl'

media_folder: 'static/api'

collections:
  - name: posts
    label: 'Wpisy'
    folder: 'wpisy'
    slug: '{{title}}'
    path: '{{year}}/{{month}}/{{day}}/{{slug}}'
    preview_path: 'kronika/{{year}}/{{month}}/{{day}}/{{title}}'
    preview_path_date_field: 'date'
    create: true
    editor:
      preview: false
    fields:
      - label: 'Tytuł'
        name: title
        widget: string
        required: true

      - label: 'Autor'
        name: author
        widget: string
        required: true

      - label: 'Data'
        name: date
        widget: datetime
        dateFormat: DD.MM.YYYY
        timeFormat: false
        required: true

      - label: 'Kategorie/Tagi'
        name: category
        widget: list
        required: false

      - label: 'Zdjęcie okładki - link'
        name: image
        widget: string
        required: false

      - label: 'Wpis'
        name: body
        widget: markdown
        required: true
