backend:
  name: git-gateway

publish_mode: editorial_workflow
display_url: https://puszcza.netlify.app
site_url: https://puszcza.netlify.app
logo_url: /19pdh.png
locale: 'pl'

media_folder: 'static/s'

collections:
  - name: posts
    label: 'Wpisy'
    label_singular: 'wpis'
    folder: 'wpisy'
    slug: '{{title}}'
    path: 'kronika/{{year}}/{{month}}/{{day}}/{{slug}}'
    preview_path: 'kronika/{{year}}/{{month}}/{{day}}/{{title}}'
    preview_path_date_field: 'date'
    create: true
    editor:
      preview: true
    fields:
      - label: 'Tytuł'
        name: title
        widget: string
        required: true

      - label: 'Kategorie/Tagi'
        name: category
        widget: list
        required: false

      - label: 'Wpis'
        name: body
        widget: markdown
        required: true
