#!/bin/sh
## Automated script for compiling lowdown

# jekyll-cache is cached by netlify plugin
mkdir -p .jekyll-cache

## lowdown
if [ ! -f .jekyll-cache/lowdown ]; then
  wget https://kristaps.bsd.lv/lowdown/snapshots/lowdown.tar.gz
  tar xf lowdown.tar.gz
  cd lowdown-*
  ./configure
  make
  cp lowdown ../.jekyll-cache
  cd ..
fi


## cpio
if [ ! -d .jekyll-cache/cpio_src ]; then
  wget https://ftp.gnu.org/gnu/cpio/cpio-2.13.tar.gz
  tar xf cpio-2.13.tar.gz
  cd cpio-2.13
  ./configure --prefix=$PWD/out
  make
  make install
  cp -r out ../.jekyll-cache/cpio_src
  ln -s ../.jekyll-cache/cpio_src/bin/cpio ../.jekyll-cache/cpio
fi
