#!/bin/sh
## Automated script for compiling lowdown

# node_modules is cached by netlify
mkdir -p node_modules

## lowdown
if [ ! -f node_modules/lowdown ]; then
  wget https://kristaps.bsd.lv/lowdown/snapshots/lowdown.tar.gz
  tar xf lowdown.tar.gz
  cd lowdown-*
  ./configure
  make
  cp lowdown ../node_modules
  cd ..
fi


## cpio
if [ ! -d node_modules/cpio_src ]; then
  wget https://ftp.gnu.org/gnu/cpio/cpio-2.13.tar.gz
  tar xf cpio-2.13.tar.gz
  cd cpio-2.13
  ./configure --prefix=$PWD/out
  make
  make install
  cp -r out ../node_modules/cpio_src
  ln -s ../node_modules/cpio_src/bin/cpio ../node_modules/cpio
fi
