name: Rebuild page

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Rebuild https://puszcza.netlify.app
      uses: wei/curl@v1
      with:
        args: -X POST -d {} https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_MASTER }}
    - name: Rebuild https://develop--puszcza.netlify.app
      uses: wei/curl@v1
      with:
        args: -X POST -d {} https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_DEVELOP }}
    - name: Rebuild https://low-puszcza.netlify.app
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: 19pdh/low-puszcza
        event-type: update
